# Utiliser une image Node.js compatible
FROM node:22.7.0

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code dans le conteneur
COPY . .

# Construire l'application
RUN npm run build

# Exposer le port utilisé par Vite (par défaut 5173 ou celui que tu utilises)
EXPOSE 5173

# Démarrer l'application en mode preview
CMD ["npm", "run", "preview"]
