services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: 
      context: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "3001:3000"  # Cela exposera le port 3000 du conteneur sur le port 3001 de l'hôte
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=SafeSpace
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=postgres
    volumes:
      - backend_code:/backend
      - backend_backups:/backend/backups

volumes:
  postgres_data:
  backend_code:
  backend_backups: