FROM node:latest

WORKDIR /backend

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

RUN apt-get update && apt-get install -y postgresql-client

RUN mkdir -p /backend/backups && chmod 777 /backend/backups

EXPOSE 3000

CMD ["npm", "run", "dev"]