FROM node:20

WORKDIR /backend

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

RUN apt-get update && apt-get install -y wget gnupg2 lsb-release
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
RUN apt-get update && apt-get install -y postgresql-client-16

RUN npm run build

RUN mkdir -p /backend/backups && chmod 777 /backend/backups

EXPOSE 3000

CMD ["npm", "run", "dev"]